### PR TITLE
Fix alignment of INPUT on 64-bit systems

### LINKED ISSUE #309: SendInput/struct INPUT doesn't work on x64
The FieldOffset for the union must be 8 instead of 4 on x64.

https://github.com/AArnott/pinvoke/blob/3ed1db34699c1d836f4db735f13c7dfe4617c900/src/User32.Desktop/User32%2BINPUT.cs

Other sources/explanations:
http://www.pinvoke.net/default.aspx/Structures/INPUT.html
https://social.msdn.microsoft.com/Forums/en-US/69e5529e-372b-4d70-bb94-556507a2358e/sendinput-vs-windows-7-x64-rc-build-7000-not-working?forum=Vsexpressvb

### PR DESCRIPTION
**Pull request by AArnott**
Bump version to 0.4 due to the breaking change.

Fixes #309

### CODE REVIEW

**Review by vbfox — APPROVED** [review]
Code seemed correct & I tested on 32 & 64 bits and the alignment is 4 & 8 as expected.

(I can't seem to build the solution anymore but I used the CI feed to test)

**Comment by vbfox** [comment]
(Native alignment rules are a pain in the ass, interesting to see that we can't avoid reproducing nested unions like that to get the same effect, I suspect quite a lot of pinvoke.net signatures erasing the unions are actually incorrect)

**Comment by AArnott** [comment]
Thank you for testing, @vbfox. If they're something you can share, it would be great to have in unit tests.
In fact we might want to split our unit test project to enforce x86 and x64 testing and use a Shared Project so the tests are in both projects.

**Comment by vbfox** [comment]
My test was running the same code in cpp

```cpp
int main()
{
	INPUT input;
	printf("hi=%i\n", (long long)&input.hi - (long long)&input);
	printf("mi=%i\n", (long long)&input.mi - (long long)&input);
	printf("ki=%i\n", (long long)&input.ki - (long long)&input);
	return 0;
}
```
And C#

```csharp
unsafe void Main()
{
	INPUT input;
	Console.WriteLine("hi={0}", (long)&input.Inputs.hi - (long)&input);
	Console.WriteLine("mi={0}", (long)&input.Inputs.mi - (long)&input);
	Console.WriteLine("ki={0}", (long)&input.Inputs.ki - (long)&input);
}
```

In both x64 & x86 and checking that the result match. Being able to have unit tests that check that the value are correct in both x86 & x64 would be perfect regresion-wise.

**Pull request merged**
