### PR TITLE
Add missingCreateProcessFlags values

### PR DESCRIPTION
**Pull request by aluferYochay**

### CODE REVIEW

**Comment by AArnott** [comment]
Thanks!

**Comment by aluferYochay** [comment]
No problem  :-)
BTW -  do you have estimation when my last PRs will be part of an official version ?

Thanks
Yochay

**Comment by AArnott** [comment]
Within a few days, likely. Perhaps even later today. In the meantime, you can [get packages now](https://github.com/AArnott/pinvoke/blob/master/CONTRIBUTING.md#self-service-releases-for-contributors)

**Comment by AArnott** [comment]
0.3.90 is being released right [now](https://ci.appveyor.com/project/AArnott/pinvoke/deployment/363576)

**Pull request merged**
