### PR TITLE
Make methods that close handles private

### PR DESCRIPTION
**Pull request by AArnott**
@vbfox: can you cast your opinion on this as well?

### CODE REVIEW

**Comment by vbfox** [comment]
Completely agreed, the only cases where someone would need to call this is because they have additional custom wrappers in their code. But then they can convert to the SafeHandle types easily (And should send a PR to add them here)

**Comment by jmelosegui** [comment]
That should be part of the [contributing](https://github.com/AArnott/pinvoke/blob/master/CONTRIB.md) help document.

**Comment by AArnott** [comment]
@jmelosegui What should? This PR itself includes an enhancement to the contributing document. Is that what you meant, or something more?

**Comment by jmelosegui** [comment]
Never mind, sorry.

**Pull request merged**
