### PR TITLE
Excluding CodeGeneration dlls from nuget package referencing them.

### PR DESCRIPTION
**Pull request by jmelosegui**
This is my attempt to solve #160. 
It is definitely excluding `CodeGenerationAttributes.Net40.dll` and `CodeGenerationAttributes.dll` from `PInvoke.Kernel32.nupkg`, I don't know if this is the right solution though.

### CODE REVIEW

**Comment by jmelosegui** [comment]
If this is the way to go I can modify all project referencing the code generation dlls and the template projects `LIBNAME` and `LIBNAME.Desktop` with the same changes.

**Comment by AArnott** [comment]
Thanks so much for catching this and authoring the fix.

> If this is the way to go I can modify all project referencing the code generation dlls and the template projects 

Yes, this looks appropriate. After you modify the rest of the projects and templates feel free to merge. But double-check that it's just as effective on at least one of the other packages as it was on kernel32 please, since nuproj has interesting p2p logic.

**Comment by vbfox** [comment]
I noticed the added dependency and wondered if it was really necessary. It's really cool that it can be removed.

**Comment by AArnott** [comment]
:+1:

**Pull request merged**
