### PR TITLE
Add CreateFile overload that doesn't require a string object

### PR DESCRIPTION
**Pull request by AArnott**

### CODE REVIEW

**Comment by qmfrederik** [comment]
nit: would it be possible to have `System.ReadOnlySpan<byte>`, too?

**Comment by AArnott** [comment]
@qmfrederik said:

> would it be possible to have System.ReadOnlySpan<byte>, too?

We *could*, but it wouldn't convey that it should be UTF-16 encoded. But given a `ReadOnlySpan<byte>`, you can readily cast to `ReadOnlySpan<char>` (i.e. without copying data) using this:

```cs
ReadOnlySpan<byte> bytes; // initialized elsewhere, assumed to be UTF-16 encoded chars
ReadOnlySpan<char> chars = MemoryMarshal.Cast<byte, char>(bytes);
```

**Comment by qmfrederik** [comment]
Fair enough, thanks!

**Comment by qmfrederik** [comment]
@AArnott Thanks. Is CI still configured for this repo? Looks like the last CI run dates from early October?

**Comment by AArnott** [comment]
@qmfrederik Oh, snap. Ya Azure Pipelines triggers broke for GitHub triggers all over the place. I finally found a workaround but hadn't applied it to this one. I've fixed it and queued another CI build.

**Pull request merged**
