### PR TITLE
Put WNDCLASS fields in the correct order

### PR DESCRIPTION
**Pull request by jnm2**
https://msdn.microsoft.com/library/windows/desktop/ms633577

Caused no small amount of head scratching until I saw it!

### CODE REVIEW

**Comment by vbfox** [comment]
Nice I checked the PR that introduced it and 4 structs had member that were alphabetically ordered:

* `WNDCLASS` (Fixed since then)
* `WNDCLASSEX` (Fixed since then except for theses 2 fields)
* `MINMAXINFO` (Still bad)
* `WINDOWINFO` (Still bad)

I'll PR the 2 other

**Review by vbfox — APPROVED** [review]

**Review by AArnott — APPROVED** [review]
Thanks! And sorry for the time you lost in head scratching.

**Comment by jnm2** [comment]
> Thanks! And sorry for the time you lost in head scratching.

I appreciate that, but no need. If it wasn't this it would have been something else, and I'm okay with that or I wouldn't make a good programmer! 😊

**Comment by AArnott** [comment]
This is published to nuget.org now, btw

**Pull request merged**
