### PR TITLE
Add pseudo console APIs

### LINKED ISSUE #430: Support pseudo console api
As of RS5 kernel32.dll now has the following three methods

- [`CreatePseudoConsole`](https://docs.microsoft.com/en-us/windows/console/createpseudoconsole)
- [`ResizePseudoConsole`](https://docs.microsoft.com/en-us/windows/console/resizepseudoconsole)
- [`ClosePseudoConsole`](https://docs.microsoft.com/en-us/windows/console/closepseudoconsole)

### PR DESCRIPTION
**Pull request by AArnott**
Closes #430

### CODE REVIEW

**Comment by AArnott** [comment]
@zoeyr do you want to review this?
I'm still using `SafeObjectHandle` instead of `SafeFileHandle` because we still target netstandard1.1 (which goes away in #476). I may be able to "get this right" if that PR completes soon.

**Comment by ghost** [comment]
Probably best to also have @zadjii-msft or @dhowett take a look as well.

**Comment by AArnott** [comment]
If it's not too hard, we can add unit tests for these p/invoke methods as well.

**Review by DHowett — APPROVED** [review]
This seems like a good and correct mechanical translation of these APIs. Thanks!

**Pull request merged**
