### PR TITLE
Refactor FacilityCode bitshift op to Facility properties

### LINKED ISSUE #604: Refactor FacilityCode bitshift op to Facility properties
Simply put, this implies moving the bitshift operation out of the enum definition and into the NTSTATUS.Facility and HResult.Facility properties.
This is more or less the same as what was done to solve #600.

This solution grants users of this library easier understanding of the FacilityCode enum values.

Files to be modified:
- HResult+FacilityCode.cs
- HResult.cs
- HResultFacts.cs
- NTStatus+FacilityCode.cs
- NTStatus.cs
- NTStatusFacts.cs
- PublicAPI.Shipped.txt

### PR DESCRIPTION
**Pull request by BinToss**
closes #604

* refactor bit shift op of enum NTSTATUS/HResult.FacilityCode
to properties NTSTATUS.Facility and HResult.Facility,
respectively.
* refactor NTSTATUSFacts, HResultFacts
* update public API sheet

BREAKING CHANGE
* All values of enum HResult.FacilityCode, NTSTATUS.FacilityCode have changed!

### CODE REVIEW

**Review by AArnott — APPROVED** [review]

**Comment by AArnott** [comment]
Thank you for these submissions!

**Comment by AArnott** [comment]
@bintoss Do you think you can finish getting this to build?

**Comment by BinToss** [comment]
Compiles with warnings now. I'm pretty sure they existed before I started on these two pull requests.

I'd also noticed the Solution file contains a path to a missing file at [L22](https://github.com/dotnet/pinvoke/blob/main/src/PInvoke.sln#L22). The file "..\tools\Update-CoverageReport.ps1" doesn't exist.

```
C:\Repos\BinToss\pinvoke [pr/RefactorFacilityCode ≡ +0 ~2 -0 !]> dotnet build .\src\Windows.Core\Windows.Core.csproj --framework net45
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.87
  CodeGenerationAttributes -> C:\Repos\BinToss\pinvoke\bin\Debug\netstandard2.0\CodeGenerationAttributes.dll
  CodeGeneration -> C:\Repos\BinToss\pinvoke\bin\Debug\netstandard2.0\CodeGeneration.dll
  CodeGenerationAttributes -> C:\Repos\BinToss\pinvoke\bin\Debug\net45\CodeGenerationAttributes.dll
C:\Repos\BinToss\pinvoke\src\Windows.Core\HResult+FacilityCode.cs(90,13): warning RS0016: Symbol 'FACILITY_LEAP' is not part of the declared API. [C:\Repos\BinToss\pinvoke\src\Windows.Core\Windows.Core.csproj]
C:\Repos\BinToss\pinvoke\src\Windows.Core\HResult+FacilityCode.cs(137,13): warning RS0016: Symbol 'FACILITY_AUDIOSTREAMING' is not part of the declared API. [C:\Repos\BinToss\pinvoke\src\Windows.Core\Windows.Core.csproj]
C:\Repos\BinToss\pinvoke\src\Windows.Core\PublicAPI.Shipped.txt(34,1): warning RS0017: Symbol 'PInvoke.HResult.FacilityCode.FACILITY_AUDIOSTREAMING = 1096 -> PInvoke.HResult.FacilityCode' is part of the declared API, but is either not public or could not be found [C:\Repos\BinToss\pinvoke\src\Windows.Core\Windows.Core.csproj]
C:\Repos\BinToss\pinvoke\src\Windows.Core\PublicAPI.Shipped.txt(82,1): warning RS0017: Symbol 'PInvoke.HResult.FacilityCode.FACILITY_LEAP = 2164 -> PInvoke.HResult.FacilityCode' is part of the declared API, but is either not public or could not be found [C:\Repos\BinToss\pinvoke\src\Windows.Core\Windows.Core.csproj]
  Windows.Core -> C:\Repos\BinToss\pinvoke\bin\Debug\net45\PInvoke.Windows.Core.dll

Build succeeded.

C:\Repos\BinToss\pinvoke\src\Windows.Core\HResult+FacilityCode.cs(90,13): warning RS0016: Symbol 'FACILITY_LEAP' is not part of the declared API. [C:\Repos\BinToss\pinvoke\src\Windows.Core\Windows.Core.csproj]
C:\Repos\BinToss\pinvoke\src\Windows.Core\HResult+FacilityCode.cs(137,13): warning RS0016: Symbol 'FACILITY_AUDIOSTREAMING' is not part of the declared API. [C:\Repos\BinToss\pinvoke\src\Windows.Core\Windows.Core.csproj]
C:\Repos\BinToss\pinvoke\src\Windows.Core\PublicAPI.Shipped.txt(34,1): warning RS0017: Symbol 'PInvoke.HResult.FacilityCode.FACILITY_AUDIOSTREAMING = 1096 -> PInvoke.HResult.FacilityCode' is part of the declared API, but is either not public or could not be found [C:\Repos\BinToss\pinvoke\src\Windows.Core\Windows.Core.csproj]
C:\Repos\BinToss\pinvoke\src\Windows.Core\PublicAPI.Shipped.txt(82,1): warning RS0017: Symbol 'PInvoke.HResult.FacilityCode.FACILITY_LEAP = 2164 -> PInvoke.HResult.FacilityCode' is part of the declared API, but is either not public or could not be found [C:\Repos\BinToss\pinvoke\src\Windows.Core\Windows.Core.csproj]
    4 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.66
```

**Comment by AArnott** [comment]
Thanks. In 5265f77a9e5cd2 you introduced the remaining build warnings by adding `FACILITY_AUDIOSTREAMING = 1094` in the .cs file but `FACILITY_AUDIOSTREAMING = 1096` in the .txt file (note the different ordinal values). Similar issue with `FACILITY_LEAP`. Easy fix though. Thank you very much for your contribution.

**Pull request merged**
